spring:
  application:
    name: shipment-service

data:
  dynamodb:
    entity2ddl:
      auto: none
      gsiProjectionType: ALL
      readCapacity: 10
      writeCapacity: 1

server:
  port: 12345

logging:
  level:
    root: INFO

amazon:
  aws:
    accessKey: localaccesskey
    secretKey: localsecretkey
  dynamodb:
    endpoint: http://localhost:8000
  elasticsearch:
    endpoint: localhost:9200

