package com.chub.aws.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;


@Data
@NoArgsConstructor
@DynamoDBTable(tableName = "shipment")
public class ShipmentEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String shipmentNumber;

    @DynamoDBAttribute
    private LocationEntity originLocationEntity;

    @DynamoDBAttribute
    private LocationEntity destinationLocationEntity;

    private List<OrderEntity> orderEntities = new ArrayList<>();
}
